# Configuration for the new roboclaw_driver architecture
# This is compatible with the roboclaw_driver executable (new architecture)

roboclaw_driver:
  ros__parameters:
    # Device configuration
    device_name: "/dev/roboclaw"       # Change to your device
    baud_rate: 230400                  # Serial baud rate (ignored for USB)
    device_port: 128                  # RoboClaw device address

    # Motion parameters 
    accel_quad_pulses_per_second: 1000.0
    max_linear_velocity: 0.3
    max_angular_velocity: 0.07
    max_seconds_uncommanded_travel: 0.25

    # Motor PID and QPPS configuration
    # The P, I, D and maximum quadrature pulses per second for both motors.
    # These values are for my robot. Replace them with your own values.
    # Use Basic Micro's Motion Studio to determine the values.
    m1_p: 7.26239
    m1_i: 2.43
    m1_d: 0.0
    m1_qpps: 2437
    m2_p: 7.26239
    m2_i: 1.28767
    m2_d: 0.0
    m2_qpps: 2437

    # The maximum expected current (in amps) for both motors.
    # Used for warnings and initialization.
    m1_max_current: 6.0
    m2_max_current: 6.0

    # Robot physical parameters
    wheel_radius: 0.10169
    wheel_separation: 0.345
    quad_pulses_per_meter: 1566
    quad_pulses_per_revolution: 979.62

    # Publishing configuration
    publish_odom: true
    publish_joint_states: false
    publish_tf: true
    sensor_poll_rate_hz: 20.0
    status_rate_hz: 1.0
    odom_rate_hz: 40.0

    # Joint names
    left_wheel_joint_name: "left_wheel_joint"
    right_wheel_joint_name: "right_wheel_joint"

    # Frame names
    frame_odom: "odom"
    frame_base: "base_link"

    # Safety configuration
    safety_enabled: false
    overcurrent_limit_m1: 6.0
    overcurrent_limit_m2: 6.0
    overcurrent_detect_time: 0.2
    overcurrent_clear_time: 1.0
    overcurrent_hysteresis: 0.5
    temp1_limit: 80.0
    temp2_limit: 80.0
    temp_clear_delta: 5.0
    runaway_speed_factor: 1.5
    runaway_detect_time: 0.3

    # Odometry covariance
    odom_linear_covariance: 0.0025
    odom_angular_covariance: 0.01
